server:
    port: 8080

twitch:
    tmi:
        name: iounbot
        token: oauth:m2gkosau1eg9jfleq00cc7b5ivx98d 
        
security:
    oauth2: 
        client:
            clientId: 5zah4fiectyo1ntlxxepau2iftgz0x6
            clientSecret: p9xg61xtjiyhmen145nqxdykxikhm3d
            accessTokenUri: https://api.twitch.tv/kraken/oauth2/token
            userAuthorizationUri: https://api.twitch.tv/kraken/oauth2/authorize
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: user_read
        resource: 
            prefer-token-info: false
            userInfoUri: https://api.twitch.tv/kraken